name: Merged items

# only trigger on pull request closed events
on:
  pull_request:
    types: [ closed ]

jobs:
  build-and-push-image:
    # this job will only run if the PR has been merged
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 1
      - name: Build image
        run: ./scripts/build.sh
      - name: Log in and push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
        run: |
          echo $GITHUB_TOKEN | docker login ghcr.io -u imthetom --password-stdin
          docker push ghcr.io/emotivesproject/media_api:latest
          docker push ghcr.io/emotivesproject/media_server:latest
      - name: Connect and deploy
        uses: appleboy/ssh-action@master
        env:
          GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          envs: GMAIL_PASSWORD
          script: |
            docker pull ghcr.io/emotivesproject/media_api:latest
            docker pull ghcr.io/emotivesproject/media_server:latest
            rm -R media
            git clone git@github.com:EmotivesProject/media.git
            cd media
            ./scripts/start.sh prod no $GMAIL_PASSWORD